/*
 *  -------------------------------------------------------------------------
 *  Copyright 2014 
 *  Centre for Information Modeling - Austrian Centre for Digital Humanities
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License
 *  -------------------------------------------------------------------------
 */

package org.emile.client;

public class Resources_en extends java.util.ListResourceBundle {

    public Object[][] getContents() { return contents; }

    static final Object[][] contents = 
        {
            //Menu items
           { "repository"             , "Repository" },
           { "object"            	  , "Object(s)" },
           { "extras"                 , "Extras" },
           { "window"                 , "Window" },
           { "help"                   , "Help" },
  
           { "open"                   , "Open ..." },
           { "close"            	  , "Close" },
           { "search"             	  , "Search ..." },
           { "ingest"                 , "Ingest ..." },
           { "import"            	  , "Import ..." },
           { "export"            	  , "Export ..." },
           { "maintain"            	  , "Maintain ..." },
           { "manage"             	  , "Manage Handles ..." },
           { "reorganize"             , "Reorganize ..." },
           { "aggregate"              , "Aggregate ..." },
           { "exit"                   , "Exit" },
         
           { "harvest"                , "Harvest metadata ..." },
           { "review"                 , "Review source files ..." },
           { "manageue"               , "Manage user environment ..." },
           { "view"                   , "View log ..." },
           { "managepl"        		  , "Manage pipelines ..." },
           { "preferences"            , "Preferences ..." },
           { "reorganizestorage"      , "Reorganize storage layer ..." },
           { "reorganizetriplestore"  , "Reorganize triplestores ..." },
           { "updateproperties"       , "Update system properties ..." },
           { "publish"                , "Publish local resource directory" },
           { "publishgroup"           , "Publish project on target repository" },

           
           { "about"            	  , "About ..." },
           { "guide"            	  , "User Guide ..." },
           { "training"            	  , "Training Material ..." },
           { "source"            	  , "Source" },

           { "arrange"            	  , "Arrange" },
           { "saveposition"           , "Save position" },
           { "save"                   , "Save" },
           { "copy"                   , "Copy" },
             
           // Dialog buttons
           { "edit"                   , "Edit" },
           { "update"                 , "Update" },
           { "find"            	 	  , "Find" },
           { "new"            	      , "New" },
           { "replace"            	  , "Replace" },
           { "purge"            	  , "Entomb" },
           { "refresh"            	  , "Refresh" },
           { "add"                    , "Add" },
           { "delete"                 , "Delete" },
           { "cancel"                 , "Cancel" },
           { "entomb"                 , "Entomb" },
           { "collect"                , "Collect" },
           { "versioning"             , "Versioning" },
           { "apply"             	  , "Apply" },
           { "file"            	 	  , "File" },
           { "save"            	 	  , "Save" },
           { "reset"            	  , "Reset" },
           { "create"            	  , "Create" },
           { "clone"            	  , "Clone" },
           { "sort"            	      , "Sort by ..." },
           { "cancel"            	  , "Cancel" },
           { "clear"            	  , "Clear" },
           { "yes"              	  , "Yes" },
           { "no"            	      , "No" },
           { "set"                    , "Set" },
           { "unset"                  , "Unset" },
           { "remove"                 , "Remove" },
           { "run"                    , "Run" },
           { "source"                 , "Source" },
           { "format"                 , "Format" },
           { "configure"              , "Configure" },
                         
            // Table headers
           { "pid"            	 	  , "Persistent Identifier" },
           { "title"            	  , "Title" },
           { "contentmodel"           , "Content model" },
           { "lastupdate"             , "Last update" },
           { "group"            	  , "Group" },
           { "owner"            	  , "Owner" },
           { "handle"            	  , "Handle" },
           { "derivedfrom"            , "Is derived from" },
          
           { "properties"             , "Properties" },
           { "datastreams"            , "Datastreams" },
           { "relations"              , "Memberships" },
           { "add"                    , "Add" },
           { "delete"                 , "Delete" },
           { "archive"                , "Archive" },
           { "apply"             	  , "Apply" },
           { "appears"             	  , "Object appears in" },
                  
           { "dsid"             	  , "Datastream ID" },
           { "mimetype"               , "Mimetype" },
           { "createdby"              , "Created by" },
           { "created"             	  , "Created" },
           { "modifiedby"             , "Modified by" },
           { "modified"               , "Modified" },
           { "sizemb"		          , "Size in megabytes" },
           { "of"		              , "of" },
   
           { "fileupload"         	  , "Choose file for upload"},
           { "choose"          		  , "Choose"},

           // Login Dialog
           { "username"               , "Username" },
           { "passwd"                 , "Password" },
           { "repository"             , "Repository" },
           { "login"                  , "Login" },
           { "submit"                 , "Submit" },
           { "cancel"                 , "Cancel" },
           { "openrepo"               , "Open repository" },
           { "invalidcredentials"     , "Invalid credentials for authentication on <{0}>" },

           { "askcancel"              , "Are you sure you want to cancel the {0} process?" },
           { "updatehandle"           , "updating of the Handles" },
           { "replacement"            , "Replacement" },
           { "aggregation"            , "Aggregation" },
           
           // Aggregate Dialog
           { "maggregate"             , "Aggregate metadata" },
           { "kml"          		  , "Keyhole Markup Language Metadata (OpenGIS)"},
           { "pelagios"               , "Pelagios Dataset Summary (Pelagios Network)"},
           { "cmif"          		  , "Correspondence Metadata Interchange-Format (correspSearch)"},
           { "cmdi"          		  , "Component Metadata (CLARIN)"},
           { "actlog"          	      , "Activity log:"},
           { "selobjects"		      , "{0} All selected {1} object(s) will be processed\n"},
           { "propertynotf"           , "{0} {1} Object {2} has no property {3}\n"},
           { "dsnotf"          		  , "{0} {1} is referenced in {2} not found\n"},
           { "objnotf"          	  , "{0} No corresponding {1} object(s) found in the selection\n"},
           { "errwriteds"          	  , "{0} Error writing data stream {1} of object {2}\n"},
           { "okwriteds"          	  , "{0} Data stream {1} of object {2} saved successfully\n"},
           { "askaggregate"           , "{0} corresponding {1} object(s) with all necessary properties found in the selection. Do you really want to update {2} data stream of the selected object(s)?" },
           { "asktriggerarchiving"    , "Are you sure you want to trigger background process for creating/updating archiving METS file for all modified objects in the repository. Do you really want to continue?" },
               
           // Repository- and Object Editor Dialog
           { "savedsucessfully"		  , "Data stream {0} saved successfully." },
           { "nonvalidxml"            , "No valid XML document. Datastream could not be saved." },
           { "aboutbanner"            , "CIRILO 6: A Client for FEDORA 4.x-6.x based Research Data Repositories\n(c) 2020 Johannes Stigler, johannes.stigler@uni-graz.at\nCentre for Information Modelling, University of Graz"},
           { "showbydoubleclick"      , "Show data stream content by double-clicking" }, 
           { "uploadok"               , "Datastream {0} from object {1} successfully updated with the content of {2}."   },
           { "uploadnok"              , "Error while reading file {0}." },
           { "createobject"           , "Create object" },
           { "invalidpid"             , "{0} is an invalid PID. PIDs must be valid against the regex {1}." },
           { "objcreated"             , "Object <{0}> derived from protoptype {1} for group <{2}> successfully created."},
           { "protocreated"           , "Prototype <{0}> successfully created."},
           { "objexists"              , "A data object with the persistent identifier <{0}> is already existing."},
           { "askcreateobject"        , "Would you like to create object <{0}> cloned from prototype {1}?"},
           { "internalerror"          , "Internal server error. Failed to complete the requested operation correctly."},
           { "useentombpiderr"        , "<{0}> is the persistent identifier of an entombed object and cannot be reused! "},
           { "askdeldc"               , "Are you sure you want to clear all Dublin Core fields in the form without permanent markers?" }, 
           { "entrynotvalid"          , "The entry could not be saved. The location field does not contain a valid location. \n Use one of the following notations:\n"+
        		   						"@this/o:<group id>.pipelines/<data stream id>[::<absolute file path>]\n"+
        	                            "@this/<relative path>\n"+
        		   						"<data stream id> must match the regex : \\w+[\\w\\-\\.]*\\w+\n"+
           								"<absolute file path> must be a valid path on your operating system\n"+
           								"<relative path> is a server relative URL"
           },
           { "cantdeldefpipelines"    , "Pipelines in the <System> group cannot be deleted." },
           { "askpipelineexists"      , "Data stream <{0}> already exists in object <{1}>. Do you want to overwrite it?" },
           { "pipelinessaved"         , "Changes to pipeline assignments saved sucessfully." },
           { "nopipelinechanged"      , "No changes were made to pipeline assignments." },
           { "relssaved"              , "Changes to context memberships saved sucessfully." },
           { "norelschanged"          , "No changes were made to context memberships." },
           { "novalidxml"             , "File <{0}> contains no valid XML stream. The content could not be saved." },
           { "askdelpipeline"         , "Are you sure you want to delete pipeline <{0}> for content model {1}? You delete only the entry from the list. The data and references in the repository are retained." }, 
           { "entryexists"            , "Entry <{0}> already exists!"},
           { "askcreateversion"       , "You want to create an archive version of data stream {0}. This process cannot be reverted. Do you want to continue?" },
           { "versionexists"          , "You can create only one archive version per day!" },
           { "searchrepo"             , "Search in" },
           { "fulltext"               , "PID|Title contains" },
           { "limit"                  , "Limit" },
           { "notselected"            , "[ not selected ]" },
           { "hashandle"              , "has a Handle" },
           { "searchterm"             , "<Enter search term>" },
           { "allmodels"              , "All content models" },
           { "allgroups"              , "All groups" },
           { "ldotsearch"             , "PID|Title of context contains: " },
           { "askupdateproperties"    , "Are you sure you want to update system prototypes and client properties in repository <{0}> with the content of the configuration directories?" },
           { "systempropsummary"      , "System prototypes and client properties could be updated successfully." },
           { "nosupmediatype"         , "The selected file <{0}> does not have a valid data format." },
           { "noentombsyobj"          , "System objects cannot be entombed!" },         
           { "createcontext"          , "When creating context objects use"},
           { "askdelete"              , "Do you want to delete or entomb {0} selected object(s)?"},
           { "msgdelete"              , "{0} object(s) successfully deleted from the repository."},
           { "askentomb"              , "You want to entomb {0} selected object(s). This action can not be undone! In accordance with long-term archiving philosophy, the persistent identifier of the object becomes a \"grave gift\" and cannot be reused."},
           { "askdeleteobj"           , "Do you want to delete {0} selected object(s)? This action can not be undone! "},
           { "askdeleteds"            , "Do you want to delete datastream {0} of object <{1}>? This action can not be undone! "},
           { "ask2entomb"             , "You want to entomb {0} selected object(s). Are you aware of the consequences and really sure?" },
           { "msgentomb"              , "{0} object(s) successfully entombed in the repository."},
           { "changessaved"           , "Changes were successfully saved to the properties file." },     
           { "isshownat"              , "Location" },
           { "dsidexists"             , "Data stream <{0}> already exists in object <{1}>." },
           { "outofmemmory"           , "An out of memory error occurred while uploading file <{0}>. Please contact your sysop!" },
            
           
           { "invalidconst"          , "Invalid authorization constraints!" },
           { "diffpid"               , "The selected file contains a PID definition <{0}> different from that of the current object. Do you want to continue?" },  
     
           // Preferences Dialog
           { "preferences"            , "Preferences" },
           { "general"                , "General" },
           { "cubeobjects"            , "CUBE Objects" },                  
           { "gmlobjects"             , "GML Objects" },                  
           { "lidoobjects"            , "LIDO Objects" },
           { "meiobjects"             , "MEI Objects" },
           { "metsobjects"            , "METS Objects" },
           { "ontologyobjects"        , "Ontology Objects" },
           { "rdfobjects"             , "RDF Objects" },
           { "rdoobjects"             , "RDO Objects" },
           { "rtiobjects"             , "RTI Objects" },
           { "skosobjects"            , "SKOS Objects" },
           { "storyobjects"           , "Story Objects" },
           { "spectralobjects"        , "Spectral Objects" },
           { "teiobjects"             , "TEI Objects" },
           { "pyramidaltiff"          , "Generate pyramidal tiled tiffs on image upload" },
           { "seealso"                , "See also" },
     
           { "extractdcmi"            , "Extract descriptive metadata from source" },
           { "overwritesource"        , "Overwrite source with expanded content" },
           { "applysempolicy"         , "Apply policy for extracting semantic constructs" },
           { "executecust"            , "Execute customization" },
           { "executeval"             , "Execute validation" },
           { "triggerpipelines"       , "Trigger pipelines defined via cm4f:hasXsltPipelines property" },
           { "skosify"                , "Normalize SKOS datastream via Skosify" },
           { "resolveskos"       	  , "Resolve SKOS concepts" },
           { "resolvegeonames"        , "Resolve place names against geonames.org" },
           { "acceptexclusively"      , "Accept elements with geonames.org ID exclusively" },
           { "uploadimages"           , "Upload images" },
           { "createmets"             , "Create METS data stream" },
           { "fontsize"               , "Application font size" },
           { "thecure"                , "I really like \"The Cure\" : Layout version for depressive moods" },
               
    
           // Ingest Dialog
           { "ingestobjects"          , "Ingest object(s) " },
           { "ingestfrom"             , "Ingest from" },
           { "filesystem"             , "File system" },
           { "chooseingestdir"        , "Choose ingest root directory" },
           { "chooseexportdir"        , "Choose export directory" },
           { "choosesourcedir"        , "Choose source directory" },
           { "spreadsheet"            , "Spreadsheet" },
           { "choosespreadsheet"      , "Choose spreadsheet file" },
           { "choosestylesheet"       , "Choose XSLT file" },
           { "directory"              , "Directory" },
           { "template"               , "Template" },
           { "choosetemplate"         , "Choose template file" },
           { "notavailable"           , "This function is not available for the selected content model!" },
           { "exportdatastream"       , "Save data stream in file system" },
           { "savedatastream"         , "Datastream {0} successfully saved in file {1}" },
           { "ingestsummary"          , "Ingest process successfully concluded. {0} new object(s) created and {1} existing object(s) updated." },
           { "ingesterror"            , "Some ingest tasks resulted in error. {0} new object(s) created, {1} existing object(s) updated and {2} tasks resulted in error. For more detailed information see also menu \"Extras\" item \"View log\"" },
           { "askingest"              , "Data for creating or updating {0} object(s) found in the directory {1} and its subdirectories. New objects would be created based on the content model {2}. Do you really want to ingest this data into the repository?" },
           { "asksheetingest"         , "Data for creating or updating object(s) found in spreadsheet {0}. New objects would be created based on the content model {2}. This task is executed on server side. Therefore, you cannot cancel this job. Do you really want to ingest this data into the repository? " },
           { "createobjok"            , "{0} Object <{1}> created successfully based on file {2}\n" },
           { "cloneobjok"             , "{0} Object <{1}> cloned successfully based on file {2} from prototype <{3}>.\n" },
           { "updateobjok"            , "{0} Object <{1}> updated successfully based on file {2}\n" },
           { "errcreateobj"           , "{0} An error occurred while creating object <{1}> based on file {2}: Check the \"Extras-View Log\" menu item. This error occurred on the server side when creating the object in the repository. " },
           { "errupdateobj"           , "{0} An error occurred while updating object <{1}> based on file {2}: Check the \"Extras-View Log\" menu item. This error occurred on the server side when creating the object in the repository. " },
           { "errupdateobj"           , "{0} An error occurred while updating object <{1}> based on file {2}: Check the \"Extras-View Log\" menu item. This error occurred on the server side when creating the object in the repository. " },
           { "errnopid"               , "{0} An error occurred during object creation: No predefined PID found in primary source of file {2} \n" },
           { "errentombed"            , "{0} An error occurred during object creation: A PID of an entombed object was found in primary source of file {2} \n" },
           { "errnotvalid"            , "{0} An error occurred during object creation: File {2} is not a valid XML document\n" },
           { "errisxsl"               , "{0} An error occurred during object creation: File {2} is a XSLT stylesheet. Note: Using .xml file extension for XSLT stylesheets is not a good practice. Use .xsl in future for this type of data!\n" },
           { "sheetingestsummary"     , "Ingest process from spreadsheet {0} concluded successfully." },
           { "sheetingesterror"       , "Ingest process from spreadsheet {0} ended with status code {1}. For more detailed information see menu \"Extras\" item \"View log\"" },
           { "ingestnote"             , "Note: The ingest and indexing of objects in the target repository takes place asynchronously in the background. When after the ingest objects are displayed in the client, there may be temporary differences between effectively ingested objects and the number of objects displayed." },
           { "ingestnote"             , "Note: The ingest and indexing of objects in the target repository takes place asynchronously in the background. When after the ingest objects are displayed in the client, there may be temporary differences between effectively ingested objects and the number of objects displayed." },
           { "strictmode"             , "Ingest in strict mode" },
                            
           { "pipelines"              , "Pipelines" },
           { "ingestpipelines"        , "Ingest pipelines" },
           { "disspipelines"          , "Dissemination pipelines" },
           { "metdatapipelines"       , "Descriptive metadata generation pipelines" },
           { "setpipelines"           , "Set pipelines for objects based on content model" },
           { "replaceobject"          , "Replace object(s) content" },
           { "transformations"        , "Transformations" },
           { "queries"            	  , "Queries" },
           { "dublincore"             , "Dublin Core" },
           { "version"            	  , "Version" },
           { "selected"               , "Selected context(s)" },
           { "description"            , "Description" },
           { "createversion"          , "Create new version" },
           { "mode"                   , "Mode" },
           { "noconnection"           , "Could not connect to <{0}>: Repository not found. Please contact your sysop." },
           { "nokeycloak"             , "You are trying to connect to server <{0}>, but it does not have a configured authorization server. Please contact your sysop." },
           { "nodesktop"              , "Configure your operating system to support Java Desktop class." },      
           { "hdlprefix"          	  , "Project prefix" },
           { "numberconsecutively"    , "Consecutive numbering begins with" },
           { "pipelinenotfound"       , "Could not found datastream <{0}> in object <{1}>." },
           { "locationnotfound"       , "Could not found any content under location <{0}>." },
       
           // Import Dialog
           { "askimport"              , "{0} object(s) in METS format were found in directory {1} and its subdirectories. Do you really want to import the object(s) into the repository?" },
           { "askexport"              , "{0} object(s) in METS format will be exported to directory {1}. Do you want to continue?" },
           { "exportsummary"          , "{0} of {1} object(s) in METS format written sucessfully to directory {2}." },
           { "importsummary"          , "{0} of {1} object(s) in METS format imported sucessfully into the repository." },
           { "exportobj"              , "Export object(s)" },
           { "exportdir"              , "to directory" },                
           { "importobj"              , "Import object(s)" },
           { "importdir"              , "from directory" },                
           { "collecting"             , "Gathering file information ..." },                

           
           
           
           // Harvester Dialog
           { "oaiharvester"           , "Harvest OAI-PMH metadata to " },
           { "askharvest"             , "Are you sure? You want to harvest metadata from {0}?" },
           { "provider"               , "Provider" },
           { "updated"                , "Last update" },
           { "baseurl"                , "Base URL" },
           { "prefix"                 , "Metadata prefix" },
           { "shownat"                , "Shown at" },
           { "cmodel"                 , "Content model" },
           { "owner"                  , "Owner" },
           { "fetching"               , "Fetching data from {0}" },
           { "resumption"             , "Pass {0} with resumption token {1}" },
           { "harvesting"             , "Harvest" },
           { "harveststat"            , "OAI objects were generated for {0} record(s) that were harvested by data provider {1} on namespace {2}." },
                     
           // Handle Dialog
           { "askcreatehandle"        , "Handle(s) for {0} object(s) will be created. {1} Do you want to continue?" },
           { "askupdatehandle"        , "Handle(s) of {0} object(s) will be {1}. Do you want to continue?" },
           { "handlesummary"          , "Handle(s) for {0} of {1} object(s) {2} successfully." },                
           { "hcreated"               , "created" },                
           { "deleted"                , "deleted" },                
           { "refreshed"              , "refreshed" },   
           { "projprefix"             , "Using <handle prefix>/<project prefix>.<consecutive number>:<checkdigit> syntax (e.g. <handle prefix>/{0}.{1}:9). " },   
           { "checkdigit"             , "Using <handle prefix>/<system wide consecutive number>:<checkdigit> syntax. " },   
        
           // Reorganize Dialog
           { "reorgIsRunning"         , "Triplestore reorganization is currently in progress and therefore cannot be started (again)." }, 
           { "reorgFinished"          , "Triplestore reorganization was terminated normally. Semantic data of {0} out of {1} object(s) could be rewritten successfully to connected data stores." }, 
           { "triplestoreReorg"       , "Reorganize triplestores" },
           { "reorgInfo1"             , "This action first removes all triples from semantic data stores."},
           { "reorgInfo2"             , "This can lead to incorrect API request results while the process is running."},
           { "askreorg"               , "Are you sure? You want to reorganize semantic data stores?" } ,
                     
           
           // Replace Dialog
           { "asktransf"         	  , "For all of the {0} selected object(s), that contain a data stream with name {1}, this would be replaced by a transformation of its content with the XSLT stylesheet <{2}>. Do you want to continue?" }, 
           { "askquery"         	  , "For all <Context> or <Corpus> object(s) of the selected {0}, the QUERY data stream is replaced by the given content. Do you really want to continue?" }, 
           { "askpipes"         	  , "For all <{1}> object(s) of the selected {0}, the pipeline assignments are updated with the given definitions. Do you really want to continue?" }, 
           { "askrels"         		  , "For all {0} selected object(s) the context affiliations (xsl:isMemberOf Properties) are upated with the given definitions. Do you really want to continue?" }, 
           { "replacesummary"         , "Replacements executed successfully for {0} of {1} object(s). More information about the replacements can be found on the \"General\" tab in the activity log." },
           { "noreplaceop"         	  , "No replacement operation selected!" },
           { "noxslt"         	      , "No XSLT stylesheet selected!" },
           { "noquery"         	      , "The text area does not contain a valid SPARQL query!" },
           { "norels"         	      , "No context memberships selected!" },
           { "replowner"         	  , "({0}) The ownership is set to group <{1}>\n" },
           { "replversion"         	  , "({0}) A version is generated for <{1}> data streams\n" },       
           { "replsetoai"         	  , "({0}) The OAI provider publication flag is {1}\n" },
           { "replsetlr"         	  , "({0}) The language resource flag for TEI objects is {1}\n" },
           { "replsetrefresh"         , "({0}) The content is refreshed from source\n" },
           { "forall"                 , "For all {0} selected object(s):\n" },
           { "askcontinue"         	  , "Do you really want to continue?\n" }, 
           { "changeowner"            , "Change owner" },
           { "createversion"          , "Create a version of data streams" },
           { "named"                  , " named " },
           { "setprop"                , "Set language resource property" },
           { "setdc"                  , "Set Dublin Core elements" },
           { "perfop"                 , "Perform operations" },
           { "contextmemberships"     , "Context memberships" },
           { "setcontext"             , "Set context memberships" },
           { "executexslt"            , "Execute XSLT transformation on selected data stream" },
           { "subsquery"              , "Substitute content of QUERY data stream" },
           { "langresource"           , "Mark objects of type TEI as language resource" },
           { "objectfromsource"       , "Refresh object content from source" },
           { "unchanged"              , "was not changed by the replacement operations" },
           { "faulty"                 , "an error occurred during replacement operations" },
           { "changed"                , "... ok" },
           
           // Publish Dialog
           { "invalidcred"         	  , "You have provided invalid credentials!" }, 
           { "updateresdir"           , "Resource directory of group <{0}> on host <{1}> was successfully updated." }, 
           { "deltargetdir"           , "Delete target directory before uploading" }, 
           { "localdir"               , "Local directory" }, 
           { "target"                 , "Target repository" }, 
           { "updateexistingobj"      , "Update also existing objects" }, 
           { "updateexisting"         , "Existing objects in the target repository are also updated. " },
           { "askrepupdate"           , "You want to publish project <{0}> in target repository <{1}>. {2}\nAre you really sure?" }, 
           { "migrationok"            , "{1} object(s) created/updated successfully in the target repository <{0}>." }, 
       
           // Logview Dialog
           { "logview"         		  , "Log of" },
           { "date"         		  , "Date" },
           { "uuid"         		  , "UUID" },
           { "id"         		 	  , "ID" },
           { "logger"         		  , "Logger" },
           { "level"         		  , "Level" },
           { "line"         		  , "Line" },
           { "exception"         	  , "Exception" },
           { "message"         		  , "Message" },
               
           // Open File Dialog
           { "allfiles"    	          , "All files" },
           { "lookin"         		  , "Look in" },
           { "filetype"         	  , "Files of type" },
           { "filename"         	  , "File name" },
           { "name"         		  , "Name" },
           { "list"         		  , "List" },
           { "details"         		  , "Details" },
           { "size"         		  , "Size" },
           { "type"         		  , "Type" },
           { "date"         		  , "Date" },
           { "extension"              , "Extension" },
   
           { "model"                  , "Model" },
           { "category"               , "Category" },
           { "location"               , "Location" },
           { "enterpid"               , "<Enter valid Pid/Dsid>" },
           { "choosepipeline"         , "Choose pipeline file" },
           { "managepipelines"        , "Manage pipelines" },
           { "default"                , "System" },
           { "defaultpipeline"        , "Default pipeline" },
           { "userdefined"            , "User defined " },
    
           // Review Dialog
           { "dupkey"                 , "Note: Duplicate PID!" },
           { "wrongext"               , "Note: XSLT File has a wrong extension!" },
           { "summary"                , "File verification ended normally.\n{0} files were checked.\n{1} of them are invalid and {2} have an unknown schema.\n{3} duplicate PIDs were found." },
           
           // User Management Dialog
           { "environmentmanagement"  , "User Environment Management" },
           { "askcreateprototype"     , "Would you like to create a {0} prototype for group <{1}>?" },
           { "askclose"               , "Would you like to close the connection to repository <{0}> of user <{1}> ?" },
           { "asksave"                , "Are you sure? Would you like to save the data stream {0}?" },
           { "askexit"                , "Are you sure? Would you like to close all open repositories and quit Cirilo?" },
           { "askupdatesave"          , "The content of data stream {0} has been changed. Do you want to save it?" },

           // Tooltip Messages
           { "TTsearchtermfind"       , "Find all or selected context object(s)" },
           { "TTsearchtermadd"        , "Add the search term in the input field to the list" },
           { "TTsearchtermdel"        , "Delete the selected search term from the list" },
           { "TTcontextadd"           , "Add the selected context(s) to the currently being processed object" },
           { "TTcontextdel"           , "Remove the selected context(s) from the currently being processed object" },
           { "TTobjectadd"            , "Update the selected data stream with one from your local directory" },
           { "TTobjectnew"            , "Create a new data stream in the object" },
           { "TTobjectexport"         , "Export the selected data stream to the local file directory" },
           { "TTobjectver"            , "Create a version of the selected data stream. Only one version per calendar day is possible" },
           { "TTobjectpurge"          , "Permanently remove the selected data stream from the object" },
           { "TTpipelinenew"          , "Create a new pipeline entry" },
           { "TTpipelinedel"          , "Delete the selected pipeline entry" },
           { "TTpipelineapply"        , "Update the current pipeline with the selected pipeline entry" },
           { "TTprototypeadd"         , "Clone a prototype from the given templates for the selected project" },
           { "TTprototypedel"         , "Delete the selected prototype of the current project" },
           { "TTprototypeedit"        , "Edit the selected prototype. All objects that are subsequently derived from this prototype receive its current properties" },
           { "TTprototypetitle"       , "Enter the title of the new prototype" },
           { "TTprototypetype"        , "Select the content model type of the new prototype" },        
           { "TTTheCure"              , "A change to this option will only take effect after the next program start" },
           
           { "HTuncheckdc"            , "Hint: Uncheck the 'Extract descriptive metadata from source' option to activate the DC fields" },
           { "HTreplself"             , "Hint: The character string '$self' is replaced by the PID of the current object during the replacement process" },
           { "HTassignhdl"            , "Hint: By assigning a Handle, an object is also published on the OAI provider" },
           { "HTpublishzip"           , "Hint: The contents of the given local directory would be accessible under root path <{0}>" },
           { "HTupdatetarget"         , "Hint: Objects and optionally resource directory of the selected group would be transferred to target repository"},
           { "HTonlyadded"            , "Hint: By default, only new objects are added and existing objects will never be deleted"},
           { "HTonlyselcm"            , "Note! Only objects of the selected content model are changed here."},
           { "HTstrict"               , "Hint: In strict mode only primary sources with predefined persistent identifier will create an object." },
           
           // Messages
           { "outofmemory"            , "out of memory on target repository"},
           { "cpresdir"               , "Copy resource directory to target repository"},
           { "cpprototypes"           , "Copy prototype objects to target repository"},
           { "entomedobj"             , "is a PID of an entombed object in target repository" },
           { "accessforbidden"        , "access in target repository is not permitted" },
           { "existsontarget"         , "exists in target repository; nothing was changed" },
           { "startpub"               , "-- The publication process has started" },
           { "endpub"                 , "-- The publication process has ended" }
        };    


}
